### PR TITLE
Amptek exporting with suitcase

### PR DESCRIPTION
**Pull request by mrakitin**
Discovered/fixed during the interactive session with @MikeHart85 and @cryos.

### CODE REVIEW

**Comment by mrakitin** [comment]
@gfreychet, the tests indicate a text file is missing:
```
FileNotFoundError: [Errno 2] File /home/xf12id/.ipython/profile_collection/startup/intepolation_db_sdd2.txt does not exist: '/home/xf12id/.ipython/profile_collection/startup/intepolation_db_sdd2.txt'
```
Did you add it to the repo?

**Comment by gfreychet** [comment]
> 
> 
> @gfreychet, the tests indicate a text file is missing:
> 
> ```
> FileNotFoundError: [Errno 2] File /home/xf12id/.ipython/profile_collection/startup/intepolation_db_sdd2.txt does not exist: '/home/xf12id/.ipython/profile_collection/startup/intepolation_db_sdd2.txt'
> ```
> 
> Did you add it to the repo?

Yes I did add the file and can currently see it in the SMI profile collection git repository

**Comment by mrakitin** [comment]
I see. The source of issue is that this file path is hard-coded: https://github.com/NSLS-II-SMI/profile_collection/blob/5f79875100aa8fab31f3e48aac7a096674b38b3b/startup/01-load.py#L14

I'll submit a change to make it relevant to the IPython startup dir, so the code can be:
1) Testable in the CI
2) Reusable by another user

**Comment by mrakitin** [comment]
With the approach we discussed earlier this week with @danielballan, @cryos and @MikeHart85 (using databroker v2 to use the power of catalogs), we encountered the following issue today:
```py
(collection-2020-2.0rc4) ✔ ~/.ipython/profile_collection/startup [collection-2020-2.0rc4|✔]
18:06 $ ipython
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from databroker import Broker

In [2]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mrakitin'
In [2]:

In [2]: db = Broker.named('smi')

In [3]: run = db.v2['eac4a441']

In [4]: xr = run.primary.read()

In [5]: xr[['amptek_mca_spectrum', 'amptek_energy_channels']]
Out[5]:
<xarray.Dataset>
Dimensions:                 (dim_0: 8192, dim_1: 8192, time: 1)
Coordinates:
  * time                    (time) float64 1.595e+09
Dimensions without coordinates: dim_0, dim_1
Data variables:
    amptek_mca_spectrum     (time, dim_0) int64 0 0 0 0 0 0 0 ... 0 0 0 0 0 0 0
    amptek_energy_channels  (time, dim_1) float64 -165.8 -162.7 ... 2.556e+04

In [6]: df = xr[['amptek_mca_spectrum', 'amptek_energy_channels']].to_dataframe()

In [7]: df
Out[7]:
                          amptek_mca_spectrum  amptek_energy_channels
dim_0 dim_1 time
0     0     1.595440e+09                    0             -165.830000
      1     1.595440e+09                    0             -162.696072
      2     1.595440e+09                    0             -159.562288
      3     1.595440e+09                    0             -156.428649
      4     1.595440e+09                    0             -153.295153
...                                       ...                     ...
8191  8187  1.595440e+09                    0            25540.887753
      8188  1.595440e+09                    0            25544.630209
      8189  1.595440e+09                    0            25548.372958
      8190  1.595440e+09                    0            25552.116000
      8191  1.595440e+09                    0            25555.859336

[67108864 rows x 2 columns]

In [8]:
```
This was unexpected as I thought we would get a pandas dataframe with 8192 rows and 2 columns, but it didn't quite work as it produced as many as 8192x8192 rows. That's why we had to explicitly use the values for the arrays in 1700652. Is there any way to convert it better to a dataframe?

**Comment by danielballan** [comment]
Yes. Xarray has not been told that the 8192 elements in `amptek_mca_spectrum` and the 8192 elements in `amptek_energy_channels` are aligned, that they share a coordinate system. It assigned the default coordinate system `dim_0` and `dim_1` to each, and thus when forced to put them in a table it creates 8192 ^ 2 = 67108864 rows.

In the ophyd object's `describe` method, beside the `shape`, include a `dims` that gives each of these entries the same name. Then they will be aligned.

**Comment by mrakitin** [comment]
The function from this PR was manually ported to `master` via https://github.com/NSLS-II-SMI/profile_collection/commit/19e33ec392b793e76cff11b98cf7ed2bce6f51cb. I rebased on `master` to recover the missing blank spaces.

A bug with exporting for the scans containing more than 1 count of the detector will be posted in the issues by @gfreychet later. In short, the exporting procedure is not ideal, and causes issues like:
```py
ValueError: Wrong number of items passed 1208, placement implies 2                                                                                                                                                              
 
During handling of the above exception, another exception occurred:
ValueError: Shape of passed values is (8192, 1208), indices imply (8192, 2)
 
See /var/log/bluesky/bluesky.log for the full traceback
```

**Pull request merged**
